apiVersion: v1
kind: Service
metadata:
  name: php-hello-nginx
  labels:
    app: php-hello
    tier: frontend
spec:
  ports:
    - port: 80
  selector:
    app: php-hello
    tier: frontend
  type: LoadBalancer
